version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g @nestjs/cli
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - cp -R node_modules/ dist/node_modules
      - cp Procfile dist/Procfile
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist